### ISSUE TITLE
Travis is broken

### ISSUE THREAD

**Issue by jacobtomlinson** [pangeo-data/helm-chart#68]
Travis seems to be broken 😞.

In [an announcement](https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps) in May Travis decided to migrate all the open source repos from travis-ci.org to travis-ci.com. Historically org was for open source and com was for paid users. It has been a slow process and some repos are still being moved over.

It looks like this repo has stopped building on org but hasn't started building on com. This is something we should potentially raise with Travis support.

**Comment by rabernat** [comment]
Maybe this happened because I turned off the "build pushed branches" option on travis-ci.org. It was doing some weird things with the PRs, but it might have also interfered with the master branch builds.

Turned it back on. Maybe this will fix the issue.

![image](https://user-images.githubusercontent.com/1197350/45912909-570f6a80-bdf7-11e8-890b-4e96a8ff17e9.png)

**Comment by guillaumeeb** [comment]
Travis seems to work fine, Docker images are pushed to hub. I think this can be closed.

Just one question: what does the line
> Updating pangeo/values.yaml: jupyterhub.singleuser.image: {'repository': 'pangeo/notebook', 'tag': '93765e6'}

In Travis means?

**Comment by jacobtomlinson** [comment]
Not sure. It could be something to do with chartpress. Perhaps @yuvipanda could shed some light on it?

**Comment by yuvipanda** [comment]
I think it denotes the image name and tag that are pushed to dockerhub? It also updates the `values.yaml` for the chart, which can also be published. We do so for the JupyterHub chart at https://jupyterhub.github.io/helm-chart for example.
